---
title: "Process genotype file"
author: "Kimberly Olney, Ph.D."
date: "07/18/2024"
output:
  html_document:
    df_print: paged
  pdf_document: default
params:
  args: myarg
---

# Setup
```{r setup}
knitr::opts_knit$set(root.dir = ".")
library(dplyr)
library(data.table)
```

# Metadata
```{r metadata}
# Read in metadata filtered metadata file 
metadata <- read.delim("../metadata/filtered_metadata.txt")

# Read the raw genotype file
genotype_raw <- fread("../snp_array/Filtered_n598_CWOW_genotype.raw")

# Remove the first six columns (FID, IID, PAT, MAT, SEX, PHENOTYPE)
genotype_data <- genotype_raw %>% select(-c(1:6))

# Rename the columns: SNP IDs should be the column names, Sample IDs should be the row names
colnames(genotype_data) <- c("IID", colnames(genotype_data)[-1])
rownames(genotype_data) <- genotype_data$IID
genotype_data <- genotype_data %>% select(-IID)

# Transpose the data to get SNPs as rows and samples as columns
genotype_data <- t(genotype_data)

# Save the formatted data to a file
write.table(genotype_data, file = "genotype_data.txt", sep = " ", quote = FALSE, col.names = NA)

```
