---
title: "Check SNP array"
author: "Kimberly Olney, Ph.D."
date: "07/23/2024"
output:
  html_document:
    df_print: paged
  pdf_document: default
params:
  args: myarg
---
# Setup
```{r setup}
knitr::opts_knit$set(root.dir = ".")
library(dplyr)
library(data.table)
library(MatrixEQTL)
library(ggplot2)
library(qqman)
```


# Read in CWOW metadata 
```{r CWOW}
meta <- fread("../metadata/filtered_metadata.txt",  header = TRUE)
meta$Cing.LB[is.na(meta$Cing.LB)] <- 0 # replace NA with zero for cingulate LB count 
# Subset metadata to keep columns of interest 
meta_phenos <- meta[, c(1:6,14,15,19,32)]
```

# Read in fam & pca data 
A .fam file consists of 6 columns where each row describes one sample:\
1. Family ID (FID)\
2. Individual ID (IID)\
3. Maternal ID (MID)\
4. Paternal ID (PID)\
5. Sex (1=Male,2=Female,-9=Unknown)\
6. phenotype (1=Control, 2=Case, -9=Unknown)\
```{r fam_pca}
fam <- fread("../snp_array/TOPMED_imput/final_filtered_data.fam",  header = FALSE)
# Rename columns
fam <- fam %>%
  dplyr::rename(
    FID = V1,
    IID = V2, 
    MID = V3,
    PID = V4, 
    Sex = V5,
    Pheno = V6
  )
pca <- fread("../snp_array/TOPMED_imput/final_filtered_data.pca_results.eigenvec",  header = FALSE)
# Keep only the first 5 PCs and the first two columns FID and IID 
pca_subset <- pca[, 1:7]
# Rename columns
pca_subset <- pca_subset %>%
  dplyr::rename(
    FID = V1,
    IID = V2, 
    PC1 = V3,
    PC2 = V4, 
    PC3 = V5,
    PC4 = V6,
    PC5 = V7
  )
```

# Combine PCA and metadata 
```{r merge_pca_meta}
covariates <- merge(pca_subset, meta_phenos, by = "IID")
covariates$FID.y <- NULL # repeated and okay to remove
covariates <- covariates %>%
  dplyr::rename(
    FID = IID,
    IID = FID.x, 
    Sex = Sex.x)
covariates$MID <- NULL # Missing maternal and paternal information so remove these columns
covariates$PID <- NULL

write.table(covariates, "../snp_array/covariates_and_phenotype_files/covariates_and_phenotypes_imputed.txt", row.names = FALSE, sep = "\t",  quote = FALSE)

# Braak NFT 
covariates$Braak.NFT <- as.numeric(covariates$Braak.NFT)
braak <- covariates[, c(1:2,10)]
write.table(braak, "../snp_array/covariates_and_phenotype_files/Braak_phenotypes_imputed.txt", row.names = FALSE, quote = FALSE, sep = "\t")

# Thal
covariates$Thal.amyloid <- as.numeric(covariates$Thal.amyloid)
Thal <- covariates[, c(1:2,11)]
write.table(Thal, "../snp_array/covariates_and_phenotype_files/Thal_phenotypes_imputed.txt", row.names = FALSE,  quote = FALSE, sep = "\t")

# Lewy body count 
covariates$Cing.LB <- as.numeric(covariates$Cing.LB)
LB <- covariates[, c(1:2,12)]
write.table(LB, "../snp_array/covariates_and_phenotype_files/CingLB_phenotypes_imputed.txt", row.names = FALSE, quote = FALSE, sep = "\t")
```

# Output updated metadata 
```{r meta}
n580_meta <- subset(meta, IID %in% pca_subset$IID)
write.table(n580_meta, "../metadata/n580_metadata_imputed.txt", quote = FALSE, row.names = FALSE, sep = "\t")
```





