---
title: "Age GWAS Visualization"
author: "Kimberly Olney, Ph.D."
date: "March 2026"
output: html_document
---

# Set up

```{r setup, include=FALSE}
.libPaths(c("/home/kolney/R/x86_64-pc-linux-gnu-library/"))
knitr::opts_chunk$set(echo = TRUE, root.dir = ".")

library(data.table)
library(ggmanh)
library(qqman)
library(ggplot2)

# SNP annotation table
snp_anno <- fread("../snp_array/reference/NCBI_SNP_positions_with_gene_hg19ToHg38_lift_over.tsv")
snp_anno[, `:=`(gene = Gene, rsid = names)]

# Mapping from PLINK SNP IDs (CHR:POS:REF:ALT) back to rsIDs
id_map <- fread("../snp_array/reference/CHRPOSREFALT_to_rsid.txt", header = FALSE)
setnames(id_map, c("plink_id", "rsid"))

chr_labels <- c(as.character(1:22))
dir.create("../results/gwas", recursive = TRUE, showWarnings = FALSE)
```

# Load data
```{r}
gwas <- fread("../snp_array/associations_with_imputed_snps/Age_association_imputed_covar_adj.assoc.linear")

# Keep additive test only
gwas <- gwas[TEST == "ADD"]

# Remove missing p-values
gwas <- gwas[!is.na(P)]

# Map PLINK SNP IDs back to rsIDs
gwas <- merge(gwas, id_map, by.x = "SNP", by.y = "plink_id", all.x = TRUE)

# Merge with SNP annotation
gwas_snp <- merge(gwas, snp_anno, by = "rsid", all.x = TRUE)

# Keep autosomes only
gwas_snp[, CHR := as.character(CHR)]
gwas_snp <- gwas_snp[CHR %in% chr_labels]
gwas_snp[, CHR := factor(CHR, levels = chr_labels)]

# Label suggestive hits
gwas_snp[, label := ifelse(P < 1e-5 & !is.na(gene), gene, NA)]

# Quick checks
dim(gwas_snp)
head(gwas_snp[, .(rsid, SNP, CHR, BP, P, gene)])
```

# plot
```{r}
age_colors <- c("#ce8430ff", "#715434ff")

man_plot <- manhattan_plot(
  x = gwas_snp,
  pval.colname = "P",
  chr.colname = "CHR",
  pos.colname = "BP",
  plot.title = "GWAS Age",
  y.label = "-log10(p-value)",
  chr.col = age_colors,
  label.colname = "label",
  label.font.size = 2.75,
  highlight.colname = "label",
  highlight.col = "black"
)

print(man_plot)

ggsave(
  "../results/gwas/manhattan_Age.pdf",
  plot = man_plot,
  width = 8,
  height = 4.5
)

pdf("../results/gwas/qq_Age.pdf", width = 5, height = 5)
qqman::qq(
  gwas_snp$P,
  main = "QQ Plot: Age",
  pch = 18,
  col = age_colors[1],
  cex = 1.5,
  las = 1
)
dev.off()

qqman::qq(
  gwas_snp$P,
  main = "QQ Plot: Age",
  col = age_colors[1]
)
```

# save output annotations 
```{r}
fwrite(
  gwas_snp,
  "../results/gwas/Age_annotated_results.tsv",
  sep = "\t"
)
```